package com.ravimhzn.domainproperties.model

data class TrackingMetadata(
    val expHouseAndLandFilterExperiment: String,
    val location: String,
    val pageType: String,
    val searchFilterArea: List<Any>,
    val searchFilterBathroomFrom: Double,
    val searchFilterBedroomFrom: Double,
    val searchFilterCarspaceFrom: Int,
    val searchFilterExcludeDepositTaken: Boolean,
    val searchFilterExcludeUnderOffer: Boolean,
    val searchFilterInspectionsScheduled: String,
    val searchFilterLandsizeMin: Int,
    val searchFilterLocationType: String,
    val searchFilterPostcode: List<Any>,
    val searchFilterPriceMin: Int,
    val searchFilterPropertyFeatures: List<Any>,
    val searchFilterRegion: List<Any>,
    val searchFilterSuburb: List<Any>,
    val searchFilterSurroundingSuburbs: Boolean,
    val searchFiltersChanged: List<String>,
    val searchResultsCorrelationId: String,
    val searchResultsCount: Int,
    val searchResultsIncludeRecommendations: Boolean,
    val searchResultsPageDepth: String,
    val searchResultsReturnedCount: Int,
    val searchResultsReturnedListingIds: List<String>,
    val searchSortBy: String,
    val searchTerm: List<Any>,
    val searchType: String,
    val searchWidthOfSearch: Double,
    val searchWidthOfSearchType: String,
    val siteSection: String,
    val subCategory1: String
)